models/role.py
from data.db import db

class role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(250))
    state = db.Column(db.Integer)

    def __init__(self, name, description, state):
        self.name = name
        self.description = description
        self.state = state

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from config import DATABASE_CONNECTION_URI
from data.db import db

from routes.role import roles

app = Flask(__name__)

app.secret_key="tpi"

app.config['SQLALCHEMY_DATABASE_URI']=DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

db.init_app(app)

app.register_blueprint(roles)

routes/role.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.role import role
from data.db import db

roles = Blueprint('roles', __name__)

@roles.route("/", methods=["GET"])
def getAll():
    roles = role.query.all()
    return render_template('role/list.html',roles=roles)

@roles.route("/roles/<id>", methods=["GET"])
def getbyid(id):
    return "Role by id"

@roles.route("/create", methods=["POST", "GET"])
def create():
    if request.method == 'GET':
        return render_template('role/create.html')
    
    name = request.form['name']
    if name == '':
        flash("Debe ingresar el nombre","alert alert-danger")
        return redirect(url_for('roles.create'))
    
    description = request.form['description']

    new_role = role(name,description,1)

    db.session.add(new_role)
    db.session.commit()

    flash("El permiso se guardo correctamente", "alert alert-success")

    return redirect(url_for('roles.getAll'))

@roles.route("/update/<id>", methods=["POST", "GET"])
def update(id):
    if request.method == 'POST':
        updaterol = role.query.get(id)

        updaterol.name = request.form['name']
        updaterol.description = request.form['description']
        
        db.session.commit()

        flash("El permiso se actualizo correctamente")

        return redirect(url_for('roles.getAll'))
    else:    
        updaterol = role.query.get(id)
        return render_template('update.html', updates=updaterol)

@roles.route("/delete/<id>")
def delete(id):
    delrol = role.query.get(id)
    db.session.delete(delrol)
    db.session.commit()
    
    flash("El permiso se elimino correctamente")

    return redirect(url_for('roles.getAll'))

templates/index.html
{% extends 'layout.html' %}   
{% block body %}
   
    <form action="/create" method="post">
        <!-- <input type="text" name="name" placeholder="Ingrese el nombre del rol"/>
        <textarea type="text" name="description" placeholder="Ingrese la description"></textarea>

        <button>Save</button> -->
        <!-- <section id="cover" class="min-vh-100"> -->
            <div id="cover-caption">
                <div class="container">
                    <div class="row text-white">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mx-auto text-center form">
                            <h1 class="display-4 py-2 text-truncate">Crear</h1>
                            <div class="px-4">
                                <form class="justify-content-center">
                                    <div class="form-row">
                                      <div class="form-group col-md-12">
                                        <label for="inputfirstName">Nombre</label>
                                        <input type="text" class="form-control" id="inputfirstName" name="name"
                                        name="name" placeholder="Nombre">                                            
                                      </div>
                                    </div>
                                    <div class="form-row">
                                      <div class="form-group col-md-12">
                                        <label for="inputtextarea">Descripcion</label>
                                        <textarea class="form-control" rows="7"  id="inputtextarea" name="description"
                                        name="description" placeholder="Descripcion"></textarea>
                                      </div>
                                    </div>
                                    <div class="float-right p-2  pull-right">
                                      <button [routerLink]="['/Subject']" class="btn btn-primary mr-3">Cancelar</button>
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          <!-- </section> -->
    </form>

    <div>
        {% for role in roles%}
            <!-- <div>
                <h3>{{role.name}}</h3>
                <div>
                    <a href="{{ url_for('roles.update', id=role.id) }}">Update</a>
                    <a href="{{ url_for('roles.delete', id=role.id) }}">Delete</a>
                </div>
                <p>{{role.description}}</p>
            </div> -->
        {% endfor %}
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de gestion de Kayak</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body>
    {% include('partial/_navbar.html') %}
   

        <div class="container p-2">
            {% block body %}

            {% endblock%}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>

templates/partial/_message.html
{% with messages = get_flashed_messages(with_categories=true) %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="{{ category }} col-xl-11 col-lg-6 col-md-6 col-sm-6 mx-auto text-center" role="alert" id="successMessage">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

{% endwith %}

<script type="text/javascript">window.setTimeout("document.getElementById('successMessage').style.display='none';", 2000); </script>

templates/partial/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Inicio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/role/create.html
{% extends 'layout.html' %}   
{% block body %}
    <form action="/create" method="post">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-white">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mx-auto text-center form">
                            {% include 'partial/_message.html'%}
                        <div class="px-4">
                            <form class="justify-content-center">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                    <label for="inputfirstName">Nombre</label>
                                    <input type="text" class="form-control" id="inputfirstName" name="name"
                                    name="name" placeholder="Nombre">                                            
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                    <label for="inputtextarea">Descripcion</label>
                                    <textarea class="form-control" rows="7"  id="inputtextarea" name="description"
                                    name="description" placeholder="Descripcion"></textarea>
                                    </div>
                                </div>
                                <div class="float-right p-2  pull-right">
                                    <button onclick="window.location.href='role/getAll'" class="btn btn-primary mr-3">Cancelar</button>
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/role/list.html
{% extends 'layout.html' %}   
{% block body %}
    <div>
        <!-- <button class="btn btn-primary float-right" style="float: right;margin-bottom: 1%;"  >Nueva permision</button> -->
        <table class="table col-xl-6 col-lg-6 col-md-6 col-sm-6 mx-auto mt-3 ">
            <a href="{{ url_for('roles.create') }}"  style="float: right;margin-bottom: 1%;">
                <button class="btn btn-primary float-right"  >Nueva permision</button>
            </a>
            <thead class="table-dark">
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Accion</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for role in roles%}
                    <tr>
                        <td>{{role.name}}</td>
                        <td>{{role.description}}</td>
                        <td>
                            <a href="{{ url_for('roles.update', id=role.id) }}"><i class="fa-solid fa-pencil"></i></a>
                            <a href="{{ url_for('roles.delete', id=role.id) }}"><i class="fa-solid fa-trash-can"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>       
    </div>
{% endblock %}

templates/update.html
<!-- <form action="/update/{{ updates.id }}" method="post">
    <input type="text" name="name" value="{{ updates.name }}" placeholder="Ingrese el nombre del rol"/>
    <textarea type="text" name="description"  placeholder="Ingrese la description">{{ updates.description}}</textarea>

    <button>Update</button>
</form> -->

{% extends 'layout.html' %}   
{% block body %}
    <form action="/update/{{ updates.id }}" method="post">
        <div id="cover-caption">
            <div class="container">
                <div class="row text-white">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mx-auto text-center form">
                            {% include 'partial/_message.html'%}
                        <div class="px-4">
                            <form class="justify-content-center">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                    <label for="inputfirstName">Nombre</label>
                                    <input type="text" class="form-control" id="inputfirstName" name="name"
                                    name="name" placeholder="Nombre" value="{{ updates.name }}">                                            
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                    <label for="inputtextarea">Descripcion</label>
                                    <textarea class="form-control" rows="7"  id="inputtextarea" name="description"
                                    name="description" placeholder="Descripcion">{{ updates.description}}</textarea>
                                    </div>
                                </div>
                                <div class="float-right p-2  pull-right">
                                    <button onclick="window.location.href='role/getAll'" class="btn btn-primary mr-3">Cancelar</button>
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}